# Makefile for open_hiby_player

# Target executables
HOST_BIN = open_hiby_player_host
TARGET_BIN = open_hiby_player_target

# Compiler and Linker configuration
CC = gcc
CXX = g++
CROSS_CC = mipsel-linux-musl-gcc
CROSS_CXX = mipsel-linux-musl-g++

# Dependency directory names
LVGL_DIR = lvgl
DR_LIBS_DIR = dr_libs
TINYALSA_DIR = tinyalsa
FAAD2_DIR = faad2
ALAC_DIR = alac
MBEDTLS_DIR = mbedtls
CJSON_DIR = cJSON
SQLITE_DIR = sqlite3
DBUS_DIR = dbus

# Self-bootstrap: clone dependencies if they don't exist yet before evaluating variables
ifeq ($(wildcard $(LVGL_DIR)),)
$(info Cloning LVGL v9.1.0...)
$(shell git clone --depth 1 -b v9.1.0 https://github.com/lvgl/lvgl.git)
endif

# dr_flac (single-header FLAC decoder, used on both host and target)
ifeq ($(wildcard $(DR_LIBS_DIR)),)
$(info Cloning dr_libs (dr_flac)...)
$(shell git clone --depth 1 https://github.com/mackron/dr_libs.git)
endif

# tinyalsa (minimal ALSA userspace library, used on target only for audio output)
ifeq ($(wildcard $(TINYALSA_DIR)),)
$(info Cloning tinyalsa...)
$(shell git clone --depth 1 https://github.com/tinyalsa/tinyalsa.git)
endif

# FAAD2 (AAC decoder, GPLv2 -- see LICENSE and README before assuming this
# is fine for a derived project of yours)
ifeq ($(wildcard $(FAAD2_DIR)),)
$(info Cloning FAAD2...)
$(shell git clone --depth 1 https://github.com/knik0/faad2.git)
endif

# ALAC (Apple Lossless decoder, Apache 2.0 -- Apple's own reference decoder,
# mirrored by mikebrady)
ifeq ($(wildcard $(ALAC_DIR)),)
$(info Cloning ALAC...)
$(shell git clone --depth 1 https://github.com/mikebrady/alac.git)
endif

# mbedTLS (Apache 2.0 -- TLS for network streaming, subsonic_client.c). The
# real R1 firmware has no usable CA bundle (/etc/ssl/certs is empty) and its
# own libcurl/OpenSSL .so's are glibc-built and unreachable from a static
# musl binary anyway (musl's dlopen() refuses to run at all from a static
# executable -- confirmed against the real device; that's also why AAC
# ended up statically linking FAAD2 instead of dlopen()ing libfdk-aac.so.2),
# so this is vendored and cross-compiled the same way as every other
# dependency here rather than relying on anything already on the device.
ifeq ($(wildcard $(MBEDTLS_DIR)),)
$(info Cloning mbedTLS v3.6.2...)
$(shell git clone --depth 1 -b v3.6.2 https://github.com/Mbed-TLS/mbedtls.git)
endif

# cJSON (MIT, single .c/.h pair) -- both Subsonic (?f=json) and Jellyfin
# APIs speak JSON, so this avoids needing an XML parser at all.
ifeq ($(wildcard $(CJSON_DIR)),)
$(info Cloning cJSON...)
$(shell git clone --depth 1 https://github.com/DaveGamble/cJSON.git)
endif

# libdbus (AFL-2.1/GPL-2+ dual-licensed) -- target only, for the AVRCP
# transport-button service (bt_media_player.c): registers this app as a
# BlueZ org.bluez.MediaPlayer1 so a connected Bluetooth accessory's own
# play/pause/next/previous buttons control playback, which needs a real
# D-Bus service (responding to incoming method calls) rather than the
# one-shot `bluetoothctl`/`dbus-send`/`bluealsa-cli` invocations everything
# else in bluetooth_control.c uses -- no CLI tool can host a service object.
#
# Vendored and cross-compiled from source rather than dynamically linking
# against the device's own /usr/lib/libdbus-1.so.3 (confirmed present):
# that .so is built against the device's real glibc 2.22 (Ingenic vendor
# SDK, 2017), while this whole project targets mipsel-linux-musl -- musl
# and glibc are not ABI-compatible, and (per the mbedTLS comment above)
# dlopen() from a static musl binary doesn't work on this device anyway.
# Assembling a compatible glibc sysroot to link against the real .so
# properly was explored and abandoned as its own substantial, uncertain
# side project; vendoring is the same architecture every other dependency
# here already uses for exactly this class of problem (FAAD2 instead of
# dlopen()ing the device's own libfdk-aac.so.2).
#
# dbus/dbus-arch-deps.h and dbus/config.h are normally generated by
# libdbus's own CMake build from configure-time type/feature detection,
# which this project doesn't run -- see dbus_vendor_config/ (hand-written
# replacements, with their own comments on each value) and the DBUS_SRCS/
# DBUS_CFLAGS below (which exclude Windows-only sources, the dbus-daemon
# itself, service-activation spawning, and the nonce-tcp transport this
# app never uses -- confirmed via a real link+run test on the actual
# device before wiring this into the main build).
ifeq ($(wildcard $(DBUS_DIR)),)
$(info Cloning libdbus 1.16.2...)
$(shell git clone --depth 1 -b dbus-1.16.2 https://gitlab.freedesktop.org/dbus/dbus.git $(DBUS_DIR))
endif

# SQLite (public domain) -- the on-disk music library cache (metadata_db.c),
# avoiding a full re-scan + re-read of every file's tags on every boot, the
# same way the stock hiby_player caches its own library in
# usrlocal_media.db (confirmed via `file`/sqlite3's `.recover` against a real
# device's SD card: SQLite 3.x, schema 4). Vendored as the official
# amalgamation (one sqlite3.c) rather than cloning the dev tree, since
# building the amalgamation from that requires Tcl tooling this project
# doesn't otherwise need.
ifeq ($(wildcard $(SQLITE_DIR)),)
$(info Fetching SQLite 3.53.4 amalgamation...)
$(shell curl -fsSL -o /tmp/sqlite-amalgamation.zip https://www.sqlite.org/2026/sqlite-amalgamation-3530400.zip && unzip -q -o /tmp/sqlite-amalgamation.zip -d /tmp && mv /tmp/sqlite-amalgamation-3530400 $(SQLITE_DIR) && rm /tmp/sqlite-amalgamation.zip)
endif

# UI assets (theme2 -- real PNGs from the stock HiBy firmware, not ours to
# redistribute). On target these are read straight from the firmware's own
# /usr/resource/litegui/theme2 -- nothing to fetch. On host, best-effort
# mirror them from wherever the firmware happens to be unpacked locally on
# this dev machine, purely for the simulator to have something to show;
# missing assets just mean blank images on host, not a build failure.
ASSETS_DIR = assets
UNPACKED_THEME2 = ../../Hiby-R1-Mod/unpack_pack/squashfs-root/usr/resource/litegui/theme2
ifeq ($(wildcard $(ASSETS_DIR)/theme2),)
ifneq ($(wildcard $(UNPACKED_THEME2)),)
$(info Mirroring theme2 UI assets for the host simulator...)
$(shell mkdir -p $(ASSETS_DIR) && cp -r $(UNPACKED_THEME2) $(ASSETS_DIR)/theme2)
else
$(warning theme2 assets not found at $(UNPACKED_THEME2) -- host simulator will show blank images; target build is unaffected)
endif
endif

# Compile flags
# -DLV_CONF_INCLUDE_SIMPLE=1 is required to include lv_conf.h as "lv_conf.h"
CFLAGS = -O3 -g -Wall -I. -I$(LVGL_DIR) -I$(DR_LIBS_DIR) -I$(FAAD2_DIR)/include -I$(ALAC_DIR)/codec -I$(MBEDTLS_DIR)/include -I$(CJSON_DIR) -I$(SQLITE_DIR) -DLV_CONF_INCLUDE_SIMPLE=1
CXXFLAGS = $(filter-out -Wall,$(CFLAGS)) -std=c++11
HOST_CFLAGS = $(CFLAGS) -DHOST_BUILD=1 $(shell sdl2-config --cflags)
HOST_CXXFLAGS = $(CXXFLAGS) -DHOST_BUILD=1 $(shell sdl2-config --cflags)
# Optional: `make target TEST_BUILD_TAG=test25_avrcp` -- shows up in the
# About screen's version line (see build_about_screen() in gui.c) so a
# build actually running on the device can be identified without checking
# timestamps/MD5s by hand. Left unset for a normal build (About just shows
# the plain version number).
ifneq ($(TEST_BUILD_TAG),)
TEST_BUILD_TAG_DEFINE = -DTEST_BUILD_TAG=\"$(TEST_BUILD_TAG)\"
endif

# Always defined (no flag needed) -- the fallback the About screen's
# version line uses when TEST_BUILD_TAG isn't set, e.g. a real flashed
# deployment via the user's own repack process rather than an adb-pushed
# test binary. Re-evaluated (a new $(shell date ...) call) on every
# `make target` invocation, so it reflects when THIS binary was actually
# built, not when the Makefile was last edited.
BUILD_STAMP_DEFINE = -DBUILD_STAMP=\"$(shell date +%Y-%m-%d_%H:%M)\"

TARGET_CFLAGS = $(CFLAGS) -I$(LVGL_DIR)/src -I$(TINYALSA_DIR)/include -Idbus_vendor_config -I$(DBUS_DIR) $(TEST_BUILD_TAG_DEFINE) $(BUILD_STAMP_DEFINE)
TARGET_CXXFLAGS = $(CXXFLAGS) -I$(LVGL_DIR)/src -I$(TINYALSA_DIR)/include -Idbus_vendor_config -I$(DBUS_DIR) $(TEST_BUILD_TAG_DEFINE) $(BUILD_STAMP_DEFINE)
TINYALSA_CFLAGS = -O3 -g -Wall -I$(TINYALSA_DIR)/include -I$(TINYALSA_DIR)/src
# DBUS_COMPILATION/DBUS_STATIC_BUILD: libdbus's own headers gate some
# declarations on these (matching how its own build always defines them
# for an in-tree build). _GNU_SOURCE: several of libdbus's own sysdeps
# files need this for `environ`, getresuid()/getresgid(), and SO_PEERCRED
# (struct ucred) -- confirmed live via mipsel-linux-musl-gcc failing
# without it on exactly those symbols.
DBUS_CFLAGS = -O2 -Wall -D_GNU_SOURCE -DDBUS_COMPILATION -DDBUS_STATIC_BUILD -Idbus_vendor_config -I$(DBUS_DIR)
# Matches FAAD2's own CMakeLists's non-fixed-point build config
FAAD2_DEFINES = -DHAVE_INTTYPES_H=1 -DHAVE_MEMCPY=1 -DHAVE_STRING_H=1 -DHAVE_STRINGS_H=1 \
                -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_LRINTF=1 -DAPPLY_DRC -DPACKAGE_VERSION=\"2.11.2\"
FAAD2_CFLAGS = -O3 -g -Wall -I$(FAAD2_DIR)/include -I$(FAAD2_DIR)/libfaad $(FAAD2_DEFINES)
# EndianPortable.c (vendored, unmodified) only auto-detects little-endian for
# __i386__/__x86_64__/Win32 -- mipsel is little-endian too but isn't in that
# list, so without this define it silently skips byte-swapping the ALAC
# magic cookie's sampleRate field on the target build (confirmed on real
# hardware: sample_rate came out as 1152122880 instead of 44100, exactly the
# byte-reversed value). Defining it here is a no-op on host (x86_64 already
# self-detects) and the actual fix on target.
ALAC_DEFINES = -DTARGET_RT_LITTLE_ENDIAN=1
ALAC_CFLAGS = -O3 -g -Wall -I$(ALAC_DIR)/codec $(ALAC_DEFINES)
ALAC_CXXFLAGS = -O3 -g -I$(ALAC_DIR)/codec -std=c++11 $(ALAC_DEFINES)
# SQLITE_OMIT_LOAD_EXTENSION -- dlopen() doesn't work from a static musl
# binary anyway (see the mbedTLS comment above), so this just avoids
# compiling in the dead code path that would otherwise call it.
SQLITE_CFLAGS = -O3 -g -I$(SQLITE_DIR) -DSQLITE_OMIT_LOAD_EXTENSION=1

# Link flags
HOST_LDFLAGS = $(shell sdl2-config --libs) -lpthread -lm
TARGET_LDFLAGS = -static -no-pie -lpthread -lm

# Source files
APP_SRCS = src/main.c src/gui.c src/audio.c src/file_browser.c src/hw_buttons.c src/input_device_utils.c src/metadata.c src/metadata_db.c src/settings.c src/aiff_decoder.c src/dsd_filter.c src/dsd_decoder.c src/aac_decoder.c src/mp4_demux.c src/ape_demux.c src/ape_decoder.c src/peq.c src/assets.c src/screen_builders.c src/battery.c src/wifi_status.c src/ca_bundle.c src/http_client.c src/subsonic_client.c src/cover_decode.c src/asf_demux.c src/wma_decoder.c src/fallback_font.c \
src/subprocess.c src/wifi_control.c src/bluetooth_control.c src/backlight.c src/import_web.c src/airplay_control.c src/headphone_status.c src/device_config.c src/led_control.c src/charge_limiter.c src/idle_shutdown.c src/power_suspend.c src/text_reader.c src/usb_mode_control.c src/usb_dac_bridge.c src/firmware_update.c src/playlist_files.c src/timezone_data.c src/timezone_apply.c src/dlna_control.c
APP_CXX_SRCS = src/alac_decoder.cpp
LVGL_SRCS = $(shell find $(LVGL_DIR)/src -type f -name '*.c')
TINYALSA_SRCS = $(shell find $(TINYALSA_DIR)/src -type f -name '*.c')
FAAD2_SRCS = $(shell find $(FAAD2_DIR)/libfaad -type f -name '*.c')
# Decoder-only ALAC sources (the repo also ships an encoder we don't need)
ALAC_C_SRCS = $(ALAC_DIR)/codec/ag_dec.c $(ALAC_DIR)/codec/dp_dec.c $(ALAC_DIR)/codec/matrix_dec.c \
              $(ALAC_DIR)/codec/ALACBitUtilities.c $(ALAC_DIR)/codec/EndianPortable.c
ALAC_CXX_SRCS = $(ALAC_DIR)/codec/ALACDecoder.cpp
MBEDTLS_SRCS = $(shell find $(MBEDTLS_DIR)/library -type f -name '*.c')
CJSON_SRCS = $(CJSON_DIR)/cJSON.c
SQLITE_SRCS = $(SQLITE_DIR)/sqlite3.c
# Excludes (all confirmed via a real link+run test on the actual device
# before wiring this in): Windows/WinCE sources (irrelevant, this is
# Linux-only), dbus-server*.c (DBusServer is for LISTENING for incoming
# connections -- what dbus-daemon itself does; this app is purely a
# CLIENT of the already-running system bus, registering an object on an
# existing connection, never accepting one), dbus-spawn-unix.c (service
# activation -- this app never launches a D-Bus service on demand),
# dbus-test*.c (libdbus's own test harness), dbus-uuidgen.c (the
# `dbus-uuidgen` command-line tool's own main(), not library code),
# dbus-pollable-set-epoll.c (using the plain poll()-based variant instead,
# see dbus_vendor_config/config.h -- one less file, no scale need for
# epoll's advantage over poll() for this app's handful of fds),
# dbus-message-util.c (fuzzing/test helper, not needed at runtime).
DBUS_SRCS = $(filter-out %-win.c %-win32.c %wince-glue.c $(DBUS_DIR)/dbus/dbus-server%.c \
              $(DBUS_DIR)/dbus/dbus-spawn-unix.c $(DBUS_DIR)/dbus/dbus-test%.c \
              $(DBUS_DIR)/dbus/dbus-uuidgen.c $(DBUS_DIR)/dbus/dbus-pollable-set-epoll.c \
              $(DBUS_DIR)/dbus/dbus-message-util.c, \
              $(shell find $(DBUS_DIR)/dbus -maxdepth 1 -name '*.c'))
# bt_media_player.c (AVRCP transport-button service, see the DBUS_DIR
# section above) needs libdbus, so it's target-only -- not part of
# APP_SRCS (shared with the host simulator build, which has no Bluetooth
# stack to talk to anyway). Its call sites in gui.c/bluetooth_control.c
# are guarded with #ifndef HOST_BUILD for the same reason audio.c's own
# Bluetooth-output code is.
TARGET_ONLY_APP_SRCS = src/bt_media_player.c src/audio_output.c

# Object files
HOST_OBJS = $(APP_SRCS:src/%.c=build_host/%.o) $(APP_CXX_SRCS:src/%.cpp=build_host/%.o) \
            $(LVGL_SRCS:$(LVGL_DIR)/%.c=build_host/lvgl/%.o) $(FAAD2_SRCS:$(FAAD2_DIR)/libfaad/%.c=build_host/faad2/%.o) \
            $(ALAC_C_SRCS:$(ALAC_DIR)/codec/%.c=build_host/alac/%.o) $(ALAC_CXX_SRCS:$(ALAC_DIR)/codec/%.cpp=build_host/alac/%.o) \
            $(MBEDTLS_SRCS:$(MBEDTLS_DIR)/library/%.c=build_host/mbedtls/%.o) $(CJSON_SRCS:$(CJSON_DIR)/%.c=build_host/cjson/%.o) \
            $(SQLITE_SRCS:$(SQLITE_DIR)/%.c=build_host/sqlite3/%.o)
TARGET_OBJS = $(APP_SRCS:src/%.c=build_target/%.o) $(APP_CXX_SRCS:src/%.cpp=build_target/%.o) \
              $(TARGET_ONLY_APP_SRCS:src/%.c=build_target/%.o) \
              $(LVGL_SRCS:$(LVGL_DIR)/%.c=build_target/lvgl/%.o) $(TINYALSA_SRCS:$(TINYALSA_DIR)/%.c=build_target/tinyalsa/%.o) \
              $(FAAD2_SRCS:$(FAAD2_DIR)/libfaad/%.c=build_target/faad2/%.o) \
              $(ALAC_C_SRCS:$(ALAC_DIR)/codec/%.c=build_target/alac/%.o) $(ALAC_CXX_SRCS:$(ALAC_DIR)/codec/%.cpp=build_target/alac/%.o) \
              $(MBEDTLS_SRCS:$(MBEDTLS_DIR)/library/%.c=build_target/mbedtls/%.o) $(CJSON_SRCS:$(CJSON_DIR)/%.c=build_target/cjson/%.o) \
              $(SQLITE_SRCS:$(SQLITE_DIR)/%.c=build_target/sqlite3/%.o) \
              $(DBUS_SRCS:$(DBUS_DIR)/dbus/%.c=build_target/dbus/%.o)

.PHONY: all host target clean compile_commands.json

# Default target builds for host simulation and generates compile commands for IDE
all: host compile_commands.json

# Build for host (Arch Linux PC)
host: $(HOST_BIN)

$(HOST_BIN): $(HOST_OBJS)
	$(CXX) -o $@ $(HOST_OBJS) $(HOST_LDFLAGS)
	@echo "Host build complete: Run './$(HOST_BIN)' to start the simulator."

build_host/%.o: src/%.c
	@mkdir -p $(dir $@)
	$(CC) $(HOST_CFLAGS) -c $< -o $@

build_host/%.o: src/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(HOST_CXXFLAGS) -c $< -o $@

build_host/lvgl/%.o: $(LVGL_DIR)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(HOST_CFLAGS) -c $< -o $@

build_host/faad2/%.o: $(FAAD2_DIR)/libfaad/%.c
	@mkdir -p $(dir $@)
	$(CC) $(FAAD2_CFLAGS) -c $< -o $@

build_host/alac/%.o: $(ALAC_DIR)/codec/%.c
	@mkdir -p $(dir $@)
	$(CC) $(ALAC_CFLAGS) -c $< -o $@

build_host/alac/%.o: $(ALAC_DIR)/codec/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(ALAC_CXXFLAGS) -c $< -o $@

build_host/mbedtls/%.o: $(MBEDTLS_DIR)/library/%.c
	@mkdir -p $(dir $@)
	$(CC) $(HOST_CFLAGS) -c $< -o $@

build_host/cjson/%.o: $(CJSON_DIR)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(HOST_CFLAGS) -c $< -o $@

build_host/sqlite3/%.o: $(SQLITE_DIR)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(SQLITE_CFLAGS) -DHOST_BUILD=1 -c $< -o $@

# Build for target (MIPS HiBy Device)
target: $(TARGET_BIN)

$(TARGET_BIN): $(TARGET_OBJS)
	$(CROSS_CXX) -o $@ $(TARGET_OBJS) $(TARGET_LDFLAGS)
	@echo "Target build complete: File ready at '$(TARGET_BIN)'"

build_target/%.o: src/%.c
	@mkdir -p $(dir $@)
	$(CROSS_CC) $(TARGET_CFLAGS) -c $< -o $@

build_target/%.o: src/%.cpp
	@mkdir -p $(dir $@)
	$(CROSS_CXX) $(TARGET_CXXFLAGS) -c $< -o $@

build_target/lvgl/%.o: $(LVGL_DIR)/%.c
	@mkdir -p $(dir $@)
	$(CROSS_CC) $(TARGET_CFLAGS) -c $< -o $@

build_target/tinyalsa/%.o: $(TINYALSA_DIR)/%.c
	@mkdir -p $(dir $@)
	$(CROSS_CC) $(TINYALSA_CFLAGS) -c $< -o $@

build_target/faad2/%.o: $(FAAD2_DIR)/libfaad/%.c
	@mkdir -p $(dir $@)
	$(CROSS_CC) $(FAAD2_CFLAGS) -c $< -o $@

build_target/alac/%.o: $(ALAC_DIR)/codec/%.c
	@mkdir -p $(dir $@)
	$(CROSS_CC) $(ALAC_CFLAGS) -c $< -o $@

build_target/alac/%.o: $(ALAC_DIR)/codec/%.cpp
	@mkdir -p $(dir $@)
	$(CROSS_CXX) $(ALAC_CXXFLAGS) -c $< -o $@

build_target/mbedtls/%.o: $(MBEDTLS_DIR)/library/%.c
	@mkdir -p $(dir $@)
	$(CROSS_CC) $(TARGET_CFLAGS) -c $< -o $@

build_target/cjson/%.o: $(CJSON_DIR)/%.c
	@mkdir -p $(dir $@)
	$(CROSS_CC) $(TARGET_CFLAGS) -c $< -o $@

build_target/sqlite3/%.o: $(SQLITE_DIR)/%.c
	@mkdir -p $(dir $@)
	$(CROSS_CC) $(SQLITE_CFLAGS) -c $< -o $@

build_target/dbus/%.o: $(DBUS_DIR)/dbus/%.c
	@mkdir -p $(dir $@)
	$(CROSS_CC) $(DBUS_CFLAGS) -c $< -o $@

# Generate compile_commands.json for Zed/clangd LSP autofill and hover popups
compile_commands.json:
	@python3 generate_compile_commands.py

clean:
	rm -rf build_host build_target $(HOST_BIN) $(TARGET_BIN) compile_commands.json compile_flags.txt
