/* Hand-written replacement for dbus/dbus-arch-deps.h.in -- normally
 * generated by dbus's own CMake/autotools build from configure-time type
 * detection, which this project doesn't run (see Makefile's DBUS_DIR
 * section for why: vendored and cross-compiled directly, matching
 * tinyalsa/mbedTLS, rather than pulling in dbus's own build system).
 * Values below are the standard ones for any mainstream 32-bit Linux
 * target (int64_t is `long long`, int32_t is `int`, int16_t is `short`),
 * true for mipsel same as x86/ARM. */
#if !defined (DBUS_INSIDE_DBUS_H) && !defined (DBUS_COMPILATION)
#error "Only <dbus/dbus.h> can be included directly, this file may disappear or change contents."
#endif

#ifndef DBUS_ARCH_DEPS_H
#define DBUS_ARCH_DEPS_H

#include <dbus/dbus-macros.h>

DBUS_BEGIN_DECLS

#define DBUS_HAVE_INT64 1
_DBUS_GNUC_EXTENSION typedef long long dbus_int64_t;
_DBUS_GNUC_EXTENSION typedef unsigned long long dbus_uint64_t;

#define DBUS_INT64_CONSTANT(val)  (_DBUS_GNUC_EXTENSION (val##LL))
#define DBUS_UINT64_CONSTANT(val) (_DBUS_GNUC_EXTENSION (val##ULL))

typedef int dbus_int32_t;
typedef unsigned int dbus_uint32_t;

typedef short dbus_int16_t;
typedef unsigned short dbus_uint16_t;

#define DBUS_MAJOR_VERSION 1
#define DBUS_MINOR_VERSION 16
#define DBUS_MICRO_VERSION 2

#define DBUS_VERSION_STRING "1.16.2"

#define DBUS_VERSION ((1 << 16) | (16 << 8) | (2))

DBUS_END_DECLS

#endif /* DBUS_ARCH_DEPS_H */
