name: Build and Release HiBy R1 Firmware

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and setup MIPS toolchain
        run: |
          # Use curl with location redirects (-L) and 3 automatic retries
          curl -S -L -O --retry 3 https://musl.cc/mipsel-linux-musl-cross.tgz
          tar -xf mipsel-linux-musl-cross.tgz
          echo "${{ github.workspace }}/mipsel-linux-musl-cross/bin" >> $GITHUB_PATH

      - name: Compile Firmware
        run: |
          make clean
          make target

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            open_hiby_player_target
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
